import json
import configparser
import vdf
from pathlib import Path

class ConfigLoader:
    @staticmethod
    def load(file_path: Path, format: str):
        if not file_path.exists():
            return {}
        if format == "vdf":
            with open(file_path, 'r', encoding='utf-8') as f:
                data = vdf.loads(f.read())
                return data.get("Video", {})
        elif format == "json":
            with open(file_path, 'r', encoding='utf-8') as f:
                return json.load(f)
        elif format == "ini":
            config = configparser.ConfigParser()
            config.read(file_path, encoding='utf-8')
            return {section: dict(config.items(section)) for section in config.sections()}
        elif format == "keyvalue":
            data = {}
            with open(file_path, 'r', encoding='utf-8') as f:
                for line in f:
                    if "=" in line and not line.strip().startswith("//"):
                        key, val = line.strip().split("=", 1)
                        data[key.strip()] = val.strip()
            return data
        elif format == "text":
            with open(file_path, 'r', encoding='utf-8') as f:
                return {"content": f.read()}
        else:
            return {}

    @staticmethod
    def save(file_path: Path, data: dict, format: str):
        file_path.parent.mkdir(parents=True, exist_ok=True)
        if format == "vdf":
            existing = {}
            if file_path.exists():
                with open(file_path, 'r', encoding='utf-8') as f:
                    existing = vdf.loads(f.read())
            existing["Video"] = data
            with open(file_path, 'w', encoding='utf-8') as f:
                vdf.dump(existing, f, pretty=True)
        elif format == "json":
            with open(file_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2)
        elif format == "ini":
            config = configparser.ConfigParser()
            for section, values in data.items():
                config[section] = values
            with open(file_path, 'w', encoding='utf-8') as f:
                config.write(f)
        elif format == "keyvalue":
            with open(file_path, 'w', encoding='utf-8') as f:
                for key, val in data.items():
                    f.write(f"{key}={val}\n")
        elif format == "text":
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(data.get("content", ""))
        else:
            raise ValueError(f"Unsupported format: {format}")

    @staticmethod
    def save_autoexec(file_path: Path, settings: dict):
        file_path.parent.mkdir(parents=True, exist_ok=True)
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write("// Auto-generated by GameBoost AI\n")
            for key, value in settings.items():
                f.write(f"{key} {value}\n")